# Generated by Django 3.1.7 on 2021-04-15 17:49

import api.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(validators=[api.validators.duration_validator])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, validators=[api.validators.datetime_validator])),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(validators=[api.validators.duration_validator])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, validators=[api.validators.datetime_validator])),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(validators=[api.validators.duration_validator])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, validators=[api.validators.datetime_validator])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
